### PR TITLE
Allow for specific Media Controller targeted at specific apps

### LINKED ISSUE #26: Idea: support for popular chromecast apps
The current library targets Google's Default Media Receiver (message format and available operations).

However it would be nice if additional apps with their own protocol could be supported.

My idea would be something like this:
- Allow the ChromeCastClient client to use different controller implementations
- Register controller implementations along with their respective AppId
- Let ChromeCastClient automatically load the right controller for the current app

@tapanila what do you think?

Also have a look at https://github.com/balloob/pychromecast/pull/101 (here I implemented a controller for DS Audio)

### PR DESCRIPTION
**Pull request by wind-rider**
This PR is intended to fix #26 and #19 (supporting other chromecast apps that have their own protocol in a separate namespace).

For these apps the heartbeat, receiver and connection channels can be still used but the media channel needs to be implemented separately because they have their own message protocol, additional methods and additional / other info in their media status messages.

Examples are 
- DS Audio (Synology)
- DS Video (Synology)
- Youtube
- Plex
- Twitch

I started by separating the messages for the Default Media Receiver protocol from the other messages.

### CODE REVIEW

**Comment by tapanila** [comment]
I don't have a huge experience with different chromecast receiver applications. I have coded clients for 3 which were all media related applications.

All of them used the default media commands but they work by adding a lot of stuff into CustomData field. That's why I have defined CustomData as a object. If that's really not enough then I will need to do some research how much they are different from each other.

From those example the only one that I use is Plex. So I will create a sample project how to command plex and will check if changes are necessary.

**Comment by wind-rider** [comment]
I think there are three types of Chromecast apps:

1. Apps that completely follow the Default Media Receiver protocol
        These apps only talk over `urn:x-cast:com.google.cast.media`
       
    - [x] In SharpCaster these apps work
    - [ ] the media control code could be refactored to be separated from the `ChromeCastClient` class.

2. "Hybrid" apps that use the Default Media Receiver protocol, but have additional functionality
        E.g. Youtube. This app uses both `urn:x-cast:com.google.cast.media` and `urn:x-cast:com.google.youtube.mdx` (see https://www.youtube.com/s/tv/html5/d5215f76/app-prod.js):
````
            this.i = this.h.getCastMessageBus(cast.receiver.media.MEDIA_NAMESPACE, cast.receiver.CastMessageBus.MessageType.JSON);
            this.i.deserializeMessage = y(b, x(this.i.deserializeMessage, this.i));
            this.l = this.h.getCastMessageBus("urn:x-cast:com.google.youtube.mdx", cast.receiver.CastMessageBus.MessageType.JSON);
            this.l.deserializeMessage = y(b, x(this.l.deserializeMessage, this.l))
````
On the Default Media namespace it supports:
```
GET_STATUS
PLAY
PAUSE
STOP
SEEK
LOAD
QUEUE_UPDATE
```
On the mdx namespace it supports

- `flingVideo` (to start playing a youtube video id at a specific time)
- `getMdxSessionStatus` (returns a mdxSessionStatus message with a screenId in the message?)

    - [x] In SharpCaster the basis of these apps works
    - [ ] in SharpCaster not all functionality is available by default
    - [ ] CustomData field is needed
    - [ ] when the Default Media Controller code is extracted from the `ChromeCastClient` class, controllers for this type of apps could be subclassed from that new class

3. Apps that do not use the Default Media Receiver protocol
        These apps completely define their own commands and status updates. Examples are Plex, DS Audio, DS Video.

    - [ ] In SharpCaster the these apps do not work
    - [ ] CustomData field is needed
    - [ ] These apps roughly have the same functionality as the other media apps but they just have different protocols. That's why I think they should be implemented on the same level as a controller for the Default Media Receiver controller.

**Comment by tapanila** [comment]
I think following approach would be really good:

- [ ] Move logic away from ChromeCastClient into Channel classes (defaultmediachannel, hearbeatchannel, receiverchannel and connectionschannel)
- [ ] Create number of basic channels ready (youtube, plex and etc)

What do you think of that approach?

**Comment by wind-rider** [comment]
Sounds good! I just started moving the mediacontroller code to a separate class, I'm curious what you think of it.

**Comment by tapanila** [comment]
I think ChromeCastClient should contain following stuff:
- Reading packages and sending them to channels
- List of channels
- Write
- Status of Chromecast device (Status of media would belong to Media channel)
- Nothing else. Everything else that is currently there should be moved to channels

So for example when you want to do play. You would need to ask ChromeCastClient for MediaChannel and then that MediaChannel would expose the Play function. This way we can add complex logic to channels which are very specific example. plex.

I will be looking to solve the nuget issue tomorrow so I can finally merge the dev to master. After that I will take a look at this refactoring

**Comment by wind-rider** [comment]
> so I can finally merge the dev to master. After that I will take a look at this refactoring
Nice!

Let's also take inspiration from https://github.com/balloob/pychromecast.

My ideas about refactoring:
- I'm wondering whether the ChromeCastClient should have Write and ReadPackage. Shouldn't they go to Channels? After all you write something to a channel and you read from a channel.
- About the Channels vs Controllers: I think that each Channel can only handle 1 namespace. So for heartbeatChannel, connectionChannel and receiverChannel that is ok. However I think that some chromecast apps use multiple namespaces for media control (like youtube). That's why I think ChromeCastClient should have Controllers, and Controllers should have Channels. Controllers would then call Write on their Channel(s).

**Comment by tapanila** [comment]
The read needs to be on chromecastclient to decide which channel should handle the message.

Write should be moved to channels. I think adding extra controllers that handle more special cases where there is multiple namespaces makes sense.

I would create them seperately and they just configure specific channels to chromecastclient and then handle sending messages to those.

Will also check the referenced project

**Comment by wind-rider** [comment]
>  I think adding extra controllers that handle more special cases where there is multiple namespaces makes sense.
I think that having two controllers for YouTube is a bit counter-intuitive... Do you prefer that over the YouTubeController having two channels?

**Comment by wind-rider** [comment]
> The read needs to be on chromecastclient to decide which channel should handle the message.

I would move ReadPacket to the ChromeCastSocketService and let Channels / Controllers add MessageReceived callbacks to ChromeCastSocketService so that the ChromeCastSocketService will decide which Channel should handle the message

**Comment by tapanila** [comment]
Then we would need to register all the channels/controllers with socket service.

I would try to avoid putting anything more into socketservices. Since those are platform specific and will need to be coded twice

**Comment by wind-rider** [comment]
Why? All socketservice could have an abstract BaseSocketService where the Channels could be registered?

Also - by making a HeartbeatController it is possible to remove code from the SocketServices since the HeartbeatController could then contain the StartHeartbeat. Also HeartbeatChannel_MessageReceived could be moved from ChromeCastClient/

**Comment by wind-rider** [comment]
I pushed to the branch what I meant. I hope you like what you see there :)

**Comment by tapanila** [comment]
I don't like the current IMediaController interface because when we want to support new kind of commands we would need to add more stuff there and in the end it will get very bloated.

We should just simplify the IMediaController interface and create IController interface. Which in the beginning would be empty. When we more complex applications that use multiple channels then we should create a Controller that knows to which channel to command.

We should get rid of IHeartBeatController and just create new HearBeatChannel and all the logic from HearBeatController should be moved there. I think for now I would create all the channels without using Interface. Because if someone wants to create a specific implementation they should be able to remove the default implementation from Channels list and register their own.

MessageFactory should be refactored to support changing of the namespace. So we can avoid duplication of the code. (This is more for the future)

Last thing would be the BaseChromecastSocketService. I would like to avoid using base classes and for now keep the read package & Channels in ChromecastClient. Because if we use base class then ChromecastClient would need to know that our IChromecastSocketService also implements BaseChromecastSocketService to access the Channels for example or we would need to add more members into IChromecastSocketService which I would like to avoid.

**Comment by wind-rider** [comment]
> in the end it will get very bloated

yes, that's a downside. I did this to let the client application (e.g. the phone app, UWP app etc) detect which "features" are available. Do you have another idea how to do that?

> simplify the IMediaController interface and create IController interface. Which in the beginning would be empty

What would you put in IMediaController? Would MediaController classes need to implement both interfaces?

> We should get rid of IHeartBeatController and just create new HearBeatChannel and all the logic from HearBeatController should be moved there

ok. However for me it would be nice to have the difference between a IController and a Channel clear. Could you explain what would go where?

> create all the channels without using Interface

I did that mainly to prepare for unit tests. Shouldn't we keep the interfaces?

> I would like to avoid using base classes and for now keep the read package & Channels in ChromecastClient. Because if we use base class then ChromecastClient would need to know that our IChromecastSocketService also implements BaseChromecastSocketService to access the Channels for example or we would need to add more members into IChromecastSocketService which I would like to avoid.

True, however I'd rather see ChromecastClient as an orchestrator between the channels, not as a place where reading and writing logic happens. The ChromecastClient should be the main API entry for client applications I think. Do you think something like that is possible?

**Comment by tapanila** [comment]
I think we would need to have a longer chat about how to proceed with this. If you have skype just add tapanila.teemu if you prefer something else you can just drop me an email at teemu@tapanila.net

**Comment by wind-rider** [comment]
@tapanila I added you there.

**Pull request closed without merging**
