### PR TITLE
Multi platform nuget package

### PR DESCRIPTION
**Pull request by tapanila**

### CODE REVIEW

**Comment by tapanila** [comment]
I still need to add appveyor configuration and test the beta nuget package

**Comment by wind-rider** [comment]
Cool that you're working on continuous integration!

**Comment by wind-rider** [comment]
@tapanila do you want to merge this branch first or can I start merging this branch in mine to start getting my branch up to date with your work?

I don't know when you want to continue working on this PR and how much time you think it'll take?

**Comment by tapanila** [comment]
Main thing left is to test the nuget package. I'm planning to get that done tomorrow and then k will merge this to dev and then to master

**Comment by wind-rider** [comment]
Nice :) some feedback:
- why is there a separate Build solution? Can't AppVeyor use the main solution?
- it would be helpful if you would let git recognize a file to be moved/renamed. It makes merging branches easier.
    -> the csproj files are marked as being deleted and being created in another folder. Because of that my changes in these files cannot be merged with your moved files...

**Comment by tapanila** [comment]
The appveyor builds all the projects in the solutions and I want to keep the samples on the solution since I use them to do further development.

This causes problems since the UWP app doesn't have a valid packaging certificate and ms build doesn't like that and fails.

I tried to get git recognize the project files to be moved but wasn't able to do that.

**Pull request merged**
