### PR TITLE
Try using Google's official protobuf nuget packages

### PR DESCRIPTION
**Pull request by wind-rider**
I tried to create a version that uses Google's official Google.Protobuf nuget package. If we can get this to work then it will save you from maintaining your own protobuf Nuget package.

Unfortunately the official Google.Protobuf only supports the proto3 format, so I tried to update the original proto files to the proto3 syntax and generated the required classes from there.

Unfortunately I can't test it because somehow the network traffic doesn't work... It fails in the ChromecastSocketService in the while(true) loop.
First it reads a message size of 0; then while trying to read the actual message (second _client.ReadStream.ReadAsync) it fails.

Is this something you would be interested in?

### CODE REVIEW

**Comment by wind-rider** [comment]
Using your ProtoBufTester class I found out that the generated byteArray is not as expected... but I'm not sure how to debug that :/

**Comment by wind-rider** [comment]
When comparing the byte arrays it turns out that the expected byte array has 6 bytes missing at the start and 2 missing somewhere in the middle.

**Comment by Tapanila** [comment]
I would love to change into that protobuf package.

Would probably make sense to add a test project that generates the protobuf messages and we can then make sure that the produces messages match between old and new implementation.

**Comment by wind-rider** [comment]
I found a part of the problem - the generated protobuf code omits the fields that have their default values. Probably this is a proto3 feature that Chromecast (using proto2) doesn't understand :/ see https://github.com/wind-rider/SharpCaster/blob/proto3/SharpCaster/Models/Protobuf/CastChannel.cs#L267-L270

This explains the missing 5th and 6th byte and the ones in the middle, but not the missing first 4 bytes...

This could be resolved by implementing the IMessage in a custom CastMessage class ourselves instead of generating the code (or altering the WriteTo and CalculateSize methods), but it means that we can't have code generation using the official code generator...

**Comment by Tapanila** [comment]
I'm totally fine with the case that we need to manually edit the generated protobuf code. Since the models haven't changed for ages I do not see them changing frequently

**Comment by wind-rider** [comment]
I uploaded a modified version of the generated code, but I can't test it with chromecast because the connection is lost every time:

`System.IO.IOException: 'Unable to read data from the transport connection: An established connection was aborted by the software in your host machine.'`

Inner exception:
`SocketException: An established connection was aborted by the software in your host machine`

**Comment by Tapanila** [comment]
If there are any problems with the message the chromecast drops the connection right away

**Comment by wind-rider** [comment]
Do you have any guess where the 4 missing bytes come from? I read that google documentation page but there it is written that the first bytes should be the first field (field_number = 1) and instead there are 4 bytes in front of it.

Do the other messages have the same prefix?

**Comment by Tapanila** [comment]
I think all the messages have the same prefix. I have no idea why 😃

**Comment by wind-rider** [comment]
I found the prefix meaning! It is [0, 0, 0, amountOfBytesAfterThis]

**Comment by wind-rider** [comment]
Ouch, it was already in there 😳 see CastMessage.ToProto() and ByteArrayExtension.AddHeader() for example. Now modifying the code to see if that helps

**Comment by wind-rider** [comment]
The messages that derive from RequestWithId need a special way of testing since by default the RequestId always changes

**Comment by wind-rider** [comment]
@Tapanila have a look, I got it working :)

**Comment by Tapanila** [comment]
Thanks a lot! Really looking forward to merging this!

It will take me a while to review this and not sure if I'm able to do that before Build conference. So it might take a quite while to merge this, sorry for that.

**Comment by wind-rider** [comment]
Small update: [here](https://blog.oakbits.com/index.php?post/2017/02/07/Google-Cast-Protocol-%3A-Receiver-Authentication) is explained when authentication messages are used (the official client sdks seem to use them to check whether it is talking to an official chromecast).

So that means that probably we don't need to have these messages in SharpCaster as it's not required to communicate with Cast devices.

**Pull request merged**
