### PR TITLE
Make Response Exception work

### PR DESCRIPTION
**Pull request by RobertK66**
What I did:
- again a lot of refactoring's in the Tests. 
  - (first I Suspected the Static TestHelper to be/make some problems. I think I was wrong but did not change back the usage of one instance per test)
  - Made all MediaChannel tests to disconnect in the end. This really helped to stabilize Test results. Now I have deterministic results even with different internet/network timings and device states!
 
- the main thing I found was that a LOAD_ERROR never canceled the correct Task waiting for its TaskCompletionSource. The reason was that the 2nd call of TaskCompletionSourceInvoke() did not find the tcs because the 1st call already removed it!
(unfortunately I can not provoke this with a unittest. It needs my device to be connected to my current HomeAudio Client which tries immediate to reconnect on receiving of a disconnect. This is a synchronized load_App from 2 different clients where my unittest then gets the LOAD_ERROR with reason 'CANCELED'. 

- some adaption of the ChannelLogging. Now also receive Trace is logged on the Channel._logger. I think this is more consistent now

### CODE REVIEW

**Comment by Tapanila** [comment]
You are talking here about LOAD_ERROR and then you added a class called LAUNCH_ERROR.
Also the LAUNCH_ERROR could be response to launching an application?

**Comment by RobertK66** [comment]
Yes, sorry its a 'LAUNCH_ERROR'. I read my own wrong commit comment here... 

This error happens when 2 different Clients try to make LaunchApplicationAsync with different AppIDs. One gets the expected ChromecastStatus as answer, and the other one - before the fix - never gets an answer and times out on the await.

**Comment by Tapanila** [comment]
Thanks for the reply. Now it makes sense and it's great to get those error cases fixed. I noticed that there wasn't any logic to handle load media errors either when researching on this.

Can you resolve the conflicts. I will merge this after that and release a new version.

**Comment by RobertK66** [comment]
What I am not sure now is if the channel logic is consistent now. On the receiver Channel I was perfectly happy with the 'Cannot cast X to Y Exception' generated by the receive loop. I did not really dive into all of the inheritance with the "StatusChannel"s vs "normal channels". 
 I think end of the day for the client the only important thing is to get the(any) Exception and not run into useless timeout.

**Comment by Tapanila** [comment]
I agree with that. Also since there is very minimal documentation the most important thing is that there is test case showing it. So I'm very happy with the current status

**Comment by RobertK66** [comment]
Ok,  I think this code is good to go.  I checked it with a local built package and all my applications (with and without Logging) work like a charm ...

**Comment by Tapanila** [comment]
Are your applications open source? I was finally planning to write a new sample application and thinking a bit of what I would like to do with it

**Comment by RobertK66** [comment]
I do them in a public repos here:  https://github.com/RobertK66/HomeAudio  , but it is far more undocumented than your code here and I am not really prepared to give a lot of support over there.

This is more of a playground for me to experiment with stuff ( Win UI3 - sort of works/ Consolen GUI . thats it / Avalon not anything coded there / ... ) at this time.  The ConGui Project there is the one that serves my home office/JBL Speaker since i abandoned my first WPF implementation after years of using that (I think this was available open source somewhen in my fork of your sharpcaster repos years ago....)

**Comment by Tapanila** [comment]
Thanks for the link. I will take a look at AvaloniaUI and probably create a sample using it since I haven't done anything with it yet and it seems nice

**Pull request merged**
