### PR TITLE
Implement MusicTrackMediaMetadata and Fixed Bugs

### PR DESCRIPTION
**Pull request by poumason**
Implement MusicTrackMediaMetadata.
Implement idleReason of the MediaStatus,
Fixed Bugs:
1. ChromecastClient disconnection exception
2. CastMessage GetJsonType bug

### CODE REVIEW

**Comment by tapanila** [comment]
Hey,

Sorry but I will not be accepting this pull request.
Reason being that I am planning to merge Dev branch to master later today. I just will complete the Xamarin branch first and merge that to Dev.

I really liked the Disconnection state and idleReason enum. I think both of those should be added once I have completed the merging. Sorry for the inconvenience

**Comment by poumason** [comment]
No problem.
Waiting you finished merge. I will merge new master to fork branch.

**Comment by tapanila** [comment]
Done with the merging now

**Comment by poumason** [comment]
I closed the PR. 
Because the merge overwrite more codes. I think should not be auto merge.
I will sent the new PR. 
Thank you.

**Pull request closed without merging**
