### PR TITLE
Webpage Casting Code

### PR DESCRIPTION
**Pull request by kalpesh2804**
may be some improvement required but It worked fine in testing.

### CODE REVIEW

**Comment by Tapanila** [comment]
Will do a review of this ASAP and merge after confirming that it works

**Comment by Tapanila** [comment]
The code doesn't compile since the class files are missing .cs extensions and namespaces are missing.

Could you fix those?

**Comment by kalpesh2804** [comment]
I downloaded code from my branch. i am able to compile it without any issue.

**Comment by Tapanila** [comment]
Your classes are not included in the project or solutions files so they are not part of the build.

**Comment by kalpesh2804** [comment]
I updated files. please try now.

**Comment by Tapanila** [comment]
Thanks a lot. Will get back to you again after testing it

**Pull request merged**
